# Generated by Django 2.2 on 2020-04-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_user'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade_class_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_section', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.grade_section_master')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher_details')),
            ],
        ),
    ]
