# Generated by Django 2.2 on 2020-04-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_subject_and_grade_subject_grade_section_subject_master'),
        ('teacher', '0002_grade_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_subject_grade_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.grade_section_master')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.subject_master')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher_details')),
            ],
        ),
    ]
