# Generated by Django 2.2 on 2020-04-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_subject_grade_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='department_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.department')),
                ('department_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher_details')),
            ],
        ),
    ]
