# Generated by Django 2.2 on 2020-04-19 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_department_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='planners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submit', 'submit'), ('approved', 'approved'), ('resubmit', 'resubmit')], default='submit', max_length=18)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.department_head')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher_details')),
            ],
        ),
    ]
