# Generated by Django 2.2 on 2020-04-19 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0003_grade_master_grade_section_master_section_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('admission_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('S', 'STUDYING'), ('PO', 'PASSED OUT'), ('D', 'DISMISSED'), ('AD', 'ADMISSION DONE'), ('LS', 'LEAVE SCHOOL')], default='S', max_length=3)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=2)),
                ('fathers_name', models.CharField(max_length=40)),
                ('mothers_name', models.CharField(max_length=40)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('grade_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.grade_section_master')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=25)),
                ('adress2', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(default='New Delhi', max_length=25)),
                ('pincode', models.CharField(max_length=8)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student_details')),
            ],
        ),
    ]
