# Generated by Django 2.2 on 2020-04-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_grade_master_grade_section_master_section_master'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_bus_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.bus_master')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student_details')),
            ],
        ),
    ]
