# Generated by Django 2.2 on 2020-04-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_subject_grade_section'),
        ('student', '0002_student_bus_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('APPLIED LEAVE', 'APPLIED LEAVE'), ('HOLIDAY', 'HOLIDAY'), ('OTHER', 'OTHER')], default='PRESENT', max_length=16)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='attendance_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_on', models.DateField()),
                ('attendance_of', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.grade_class_teacher')),
            ],
        ),
    ]
