# Generated by Django 2.2 on 2020-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200419_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='dob',
            field=models.DateField(),
        ),
    ]
