# Generated by Django 2.2 on 2020-04-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
