# Generated by Django 2.2 on 2020-04-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
