# Generated by Django 2.2 on 2020-04-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20200419_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='section_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='grade_section_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.grade_master')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.section_master')),
            ],
        ),
    ]
