# Generated by Django 2.2 on 2020-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name_of_holiday', models.CharField(max_length=45)),
                ('event_type', models.CharField(choices=[('CBR', 'CELEBRATIONS'), ('HOLIDAYS', 'HOLIDAY'), ('GOVT', 'GOVT HOLIDAY'), ('OTHER', 'OTHER')], max_length=15)),
            ],
        ),
    ]
